export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const GET_BOOKS_SUCCESS = "GET_BOOKS_SUCCESS";
export const GET_BOOKS_FAILURE = "GET_BOOKS_FAILURE";

export const ADD_BOOKS_SUCCESS = "ADD_BOOKS_SUCCESS";
export const ADD_BOOKS_FAILURE = "ADD_BOOKS_FAILURE";

export const SNACKBAR_SUCCESS = "SNACKBAR_SUCCESS";
export const SNACKBAR_CLEAR = "SNACKBAR_CLEAR";

export const DELETE_BOOK_SUCCESS = "DELETE_BOOK_SUCCESS";
export const DELETE_BOOK_FAILURE = "DELETE_BOOK_FAILURE";

export const SINGLE_BOOK_SUCCESS = "SINGLE_BOOK_SUCCESS";
export const SINGLE_BOOK_Failure = "SINGLE_BOOK_Failure";
export const UPDATE_SINGLE_BOOK = "UPDATE_SINGLE_BOOK";
export const UPDATE_SINGLE_BOOK_FAILURE = "UPDATE_SINGLE_BOOK_FAILURE";

export const UPLOAD_COVER_PHOTO_SUCCESS = "UPLOAD_COVER_PHOTO_SUCCESS";
export const UPLOAD_COVER_PHOTO_FAILURE = "UPLOAD_COVER_PHOTO_FAILURE";

export const SINGLE_BOOK_DETAIL_SUCCESS = "SINGLE_BOOK_DETAIL_SUCCESS";
export const SINGLE_BOOK_DETAIL_FAILURE = "SINGLE_BOOK_DETAIL_FAILURE";

export const CLEAR_SINGLE_BOOK = "CLEAR_SINGLE_BOOK";
